name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.REACT_APP_API_KEY }}
      URL: ${{ secrets.REACT_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your preferred Node.js version

      - name: Install Dependencies
        run: npm ci
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './client'  # Adjust this to your build output directory
          
      - name: Install `concurrently`
        run: npm install -g concurrently

      - name: run js
        run: npm start --prefix client

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
